### ISSUE TITLE
Indexing Multicurrency

### ISSUE THREAD

**Issue by Chandrasekhar1211** [w3bdesign/algolia-woo-indexer#174]
Hi, how to define multiple currencies and product variations in class-send-products.php file to index in algolia. Those data is not indexing by default.

**Comment by w3bdesign** [comment]
@Chandrasekhar1211 

I am not sure, I have never used Woocommerce with multiple currencies before.

The plugin should support multiple product variations, but if you provide me with more details I will check it.

**Comment by Chandrasekhar1211** [comment]
Sure! my website is having two currencies i.e. USD, CAD. And have some variable products with variation swatches images. To display these items in autocomplete search, I need to index those data. Ref. Screenshot attached below. Please check.
![image](https://user-images.githubusercontent.com/106801870/234479937-225a20da-90ce-4eae-8514-7b1a0437bb92.png)

**Comment by w3bdesign** [comment]
Sorry, I haven't actively used Woocommerce for some years now, can you elaborate on how to create products with variation swatch images?

Is there a plugin or is it a builtin feature?

@Chandrasekhar1211

**Comment by Chandrasekhar1211** [comment]
We will create product attributes in that will add images for every attribute. If a product has multiple variations, we will change the product to as variable product and add these variation attributes for the specific product. The variations will show like this on the product page.
![image](https://user-images.githubusercontent.com/106801870/234649106-d3abf8f7-c1cb-49f1-ac3c-d63ac9817133.png)

**Comment by Chandrasekhar1211** [comment]
Sure, thank you.
